[package]
name = "main"
edition = "2024"

[dependencies]
windows-service = "0.8.0"
serde_json = "1.0.149"
base64 = "0.22.1"

reqwest = { version = "0.13.1", features = ["json", "blocking"] }

lib = { path = "../shared" }
