[package]
name = "kinesin"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
rand = "0.8"
sha2 = "0.10.9"
windows-service = "0.8.0"
serde_json = "1.0.149"
base64 = "0.22.1"

reqwest = { version = "0.13.1", features = ["json", "blocking"] }
