[package]
name = "builder"
edition = "2024"

[dependencies]
json_comments = "0.2.2"
serde_json = "1.0.149"

serde = { version = "1.0.228", features = ["derive"] }

lib = { path = "../shared" }
regex = "1.12.2"
